version: '3'

networks:
  node-network:
    driver: bridge

services:
  webserver:
    image: nginx:1.15.0-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - node-network

  nodeserver:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: node
    command: node /usr/src/app/index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000"
    depends_on:
      - db
      - webserver

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    tty: true
    command: --init-file /sql/init.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/sql
    environment:
      MYSQL_DATABASE: dbnode
      MYSQL_ROOT_PASSWORD: 'root'
    networks: 
      - node-network
